@baseUrl = http://localhost:3000

### Testar a Rota Base
GET {{baseUrl}}

### Registrar um Novo Usuário
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com",
  "password": "strongpassword123"
}

### Realizar Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "strongpassword123"
}

### Obter Perfil do Usuário Autenticado
@authToken = {{login.response.body.access_token}}

GET {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}

### Deletar Minha Conta
DELETE {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}

### Atualizar Meu Perfil
PATCH {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Jane Doe Updated",
  "email": "jane_new@example.com"
}

### Criar um Post
POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Olá, este é o meu primeiro post na NestSocial! 🚀"
}

### Listar Todos os Posts (Feed)
GET {{baseUrl}}/posts

### Obter um Post Específico
@postId = COLOQUE_O_ID_AQUI
GET {{baseUrl}}/posts/{{postId}}

### Atualizar um Post
PATCH {{baseUrl}}/posts/{{postId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Este post foi editado com sucesso! ✨"
}

### Deletar um Post
DELETE {{baseUrl}}/posts/{{postId}}
Authorization: Bearer {{authToken}}
