import { Heart, MessageCircle, Share2, MoreHorizontal, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Post } from '@/types/post';

interface PostCardProps {
  post: Post;
}

const PostCard = ({ post }: PostCardProps) => {
  return (
    <article className="bg-card border border-border/50 rounded-[2rem] p-6 shadow-sm transition-all duration-500 hover:shadow-md group">

      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="relative">
            <img
              src={post.author.avatar}
              alt={post.author.name}
              className="w-11 h-11 rounded-full border-2 border-background shadow-sm object-cover"
            />
            {post.isAI && (
              <div className="absolute -bottom-1 -right-1 bg-primary text-primary-foreground p-0.5 rounded-full border-2 border-background">
                <Sparkles className="w-3 h-3" />
              </div>
            )}
          </div>

          {/* Divider */}
          <div className='w-[4px] h-[40px] bg-border/50 rounded-2xl '></div>

          <div className="flex flex-col">
            <div className="flex items-center gap-1.5">
              <h4 className="font-semibold text-base leading-tight text-foreground">{post.author.name}</h4>
              {post.isAI && (
                <span className="flex items-center gap-2 bg-primary/10 text-primary text-xs font-semibold px-1.5 py-0.5 rounded-full border border-primary/20 animate-in fade-in duration-700">
                  <Bot className="w-2.5 h-2.5" />
                  AGI Agent
                </span>
              )}
            </div>
            <p className="text-base text-muted-foreground font-medium">@{post.author.username} • {post.createdAt}</p>
          </div>
        </div>

        <Button variant="ghost" size="icon" className="rounded-xl text-muted-foreground hover:bg-secondary/50">
          <MoreHorizontal className="w-5 h-5" />
        </Button>
      </div>

      {/* Content */}
      <div className="space-y-4">
        <p className="text-[16px] leading-relaxed text-foreground/90 whitespace-pre-wrap px-1">
          {post.content}
        </p>

        {/* Media Rendering */}
        {post.mediaUrl && (
          <div className="relative overflow-hidden rounded-2xl border border-border/40 bg-muted/30">
            {post.type === 'image' || post.type === 'ai' ? (
              <img
                src={post.mediaUrl}
                alt="Post content"
                className="w-full h-auto object-cover max-h-[500px] transition-transform duration-700 hover:scale-[1.02]"
                loading="lazy"
              />
            ) : post.type === 'video' ? (
              <video
                src={post.mediaUrl}
                controls
                className="w-full h-auto max-h-[500px]"
                poster={`${post.mediaUrl}?thumbnail=true`}
              />
            ) : null}

            {post.type === 'ai' && (
              <div className="absolute top-4 left-4 flex items-center gap-2 bg-black/40 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10">
                <Sparkles className="w-3.5 h-3.5 text-primary fill-primary" />
                <span className="text-xs font-semibold text-white">Generated by AI</span>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex items-center gap-1 mt-6 pt-4 border-t border-border/30">
        <Button
          variant="ghost"
          className="flex-1 rounded-xl h-11 gap-2 text-muted-foreground hover:bg-red-500/10 hover:text-red-500 transition-all duration-300 group/like"
        >
          <Heart className="w-4 h-4 transition-transform group-active/like:scale-150 group-hover/like:scale-110" />
          <span className="text-xs font-bold">{post.stats?.likes || 0}</span>
        </Button>

        <Button
          variant="ghost"
          className="flex-1 rounded-xl h-11 gap-2 text-muted-foreground hover:bg-primary/10 hover:text-primary transition-all duration-300 group/comment"
        >
          <MessageCircle className="w-4 h-4 transition-transform group-hover/comment:scale-110" />
          <span className="text-xs font-bold">{post.stats?.comments || 0}</span>
        </Button>

        <Button
          variant="ghost"
          className="flex-1 rounded-xl h-11 gap-2 text-muted-foreground hover:bg-blue-500/10 hover:text-blue-500 transition-all duration-300 group/share"
        >
          <Share2 className="w-4 h-4 transition-transform group-hover/share:scale-110" />
          <span className="text-xs font-bold">{post.stats?.shares || 0}</span>
        </Button>
      </div>
    </article>
  );
};

// Helper Icon components (inline since we imported Lucide)
const Bot = ({ className }: { className?: string }) => (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="3"
    strokeLinecap="round"
    strokeLinejoin="round"
    className={className}
  >
    <path d="M12 8V4H8" />
    <rect width="16" height="12" x="4" y="8" rx="2" />
    <path d="M2 14h2" />
    <path d="M20 14h2" />
    <path d="M15 13v2" />
    <path d="M9 13v2" />
  </svg>
);

export default PostCard;
